{% set version = "0.5-6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-km.ci
  version: {{ version|replace("-", "_") }}

source:
  fn: km.ci_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/km.ci_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/km.ci/km.ci_{{ version }}.tar.gz
  sha256: 81715339f9c711704b75c3507884904422e8d59cdd593121457abeb6e04e4ca3

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-survival
  run:
    - r-base
    - r-survival

test:
  commands:
    - $R -e "library('km.ci')"           # [not win]
    - "\"%R%\" -e \"library('km.ci')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=km.ci
  license: GPL (>= 2)
  summary: "Computes various confidence intervals for the Kaplan-Meier estimator, namely: Petos CI, Rothman CI, CI's based on Greenwoods variance, Thomas and Grunkemeier CI and the simultaneous confidence bands by Nair and Hall and Wellner."
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
