appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: n7LUSgtN8seFWlYDhydlx0zL20nDcjSTPSFpvHWW9abIL2negN2mQbTQdnyDvryOhKp04C49N9zX07L2kHnz8RAQWALewKDOiHkSv1RTc/wEYoiiC57f4HGNwc8pgC6eXymOtsaYF4MkLLj6X1GyKt+49RDjBaWM6PrbQvNAMhCSr6/5Z5J0BdXBVfVvxHlluW7isN3HAEz34V5Q9X6D2VtQuokOMxSRzjM8yseHk4whOxnWML9jQCJYdefIj83nJzt7Vc7pYNzkp/4BtEa+gQpbiKI0H3T5W7OpqeGM3QkZ1VHdRDHqyyOxlPA0RmZqHfUS8qlr8/ib2Fwz0eB3QDFYM2fzPXobodsGcY56QXXRU1+G0tKms2Nr5zM12OSa+RDSaGpaOGySIFLYrPB4zdZJzYtUuQV9Hkas6Bgofpq12RjxijOhoICiwwFIiUoziEHY/9o24fmukecvz9lbUg9Q6kugiWbY6J0y6gNbcZYHHGRzccH8XWrLKiydu4Qs2kbt80ObjrWSqCm0E7A8V+IjXk37Q/6Em/PwOifdLI/OBvcfiSWBtMx+MD6YwRbZEO6N2x2Vgw4B2v6H7f8+dVWLJRay+kRs6lV2kDetHmMFNDb5x/Ngxn7x+kJDUzTeArUlZy0oAPv5Qs7Fb/pE4z1QJSejYIHtOlh+jpy2g6M=
